# Generated by Django 4.2.5 on 2023-10-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaystreamApp', '0003_movie_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
