# Generated by Django 4.2.5 on 2023-10-05 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlaystreamApp', '0004_movie_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('poster_image', models.ImageField(blank=True, upload_to='series/posters/')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlaystreamApp.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlaystreamApp.series')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlaystreamApp.season')),
            ],
        ),
    ]
