# Generated by Django 4.2.5 on 2023-10-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaystreamApp', '0005_series_season_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
