# Generated by Django 4.2.5 on 2023-10-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaystreamApp', '0014_recentmovie_recentepisode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genre',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='series',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
